// <auto-generated />
using System;
using FileSystemWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSystemWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209201036_addIndexToTimestampOfChangeTables")]
    partial class addIndexToTimestampOfChangeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("FileSystemWeb.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "FAA6421E-6E8B-4B38-B963-28851886F08A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0F36EEAD-944A-4DB0-BFBF-F009BDCD3104",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAENBKFrGvayF7a7Ow8I+ik06fhdpchFjO4rg6OQRrFEW4XNG5JFui5aVLsGH3/KDiAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a54f369-3a45-4ab8-8d22-885a8d8b60d7",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("FileSystemWeb.Models.BigFileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BigFileUploads");
                });

            modelBuilder.Entity("FileSystemWeb.Models.FileChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("FileChanges");
                });

            modelBuilder.Entity("FileSystemWeb.Models.FileItemPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hash")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Info")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Write")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileItemPermissions");

                    b.HasDiscriminator().HasValue("FileItemPermission");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileSystemWeb.Models.FolderChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("FolderChanges");
                });

            modelBuilder.Entity("FileSystemWeb.Models.ShareFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("ShareFiles");
                });

            modelBuilder.Entity("FileSystemWeb.Models.ShareFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("ShareFolders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0B31FD59-1205-437C-AF9C-8F831C69F200",
                            ConcurrencyStamp = "A4CBB65E-6481-4FDC-A3A3-653030012687",
                            Name = "share_manager",
                            NormalizedName = "SHARE_MANAGER"
                        },
                        new
                        {
                            Id = "BE51B666-B8B0-437D-B51E-27D23D5114AB",
                            ConcurrencyStamp = "63FC4752-E000-4D96-95A2-22BBB8B862A6",
                            Name = "user_manager",
                            NormalizedName = "USER_MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_files",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.post_share_file",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_file",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_file",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.delete_share_file",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_folders",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.post_share_folder",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_folder",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.get_share_folder",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.share.delete_share_folder",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.users.post_user",
                            RoleId = "BE51B666-B8B0-437D-B51E-27D23D5114AB"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.users.post_user",
                            RoleId = "BE51B666-B8B0-437D-B51E-27D23D5114AB"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "claims/permission",
                            ClaimValue = "permissions.users.get_all_users",
                            RoleId = "BE51B666-B8B0-437D-B51E-27D23D5114AB"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "FAA6421E-6E8B-4B38-B963-28851886F08A",
                            RoleId = "0B31FD59-1205-437C-AF9C-8F831C69F200"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FileSystemWeb.Models.FolderItemPermission", b =>
                {
                    b.HasBaseType("FileSystemWeb.Models.FileItemPermission");

                    b.Property<bool>("List")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("FolderItemPermission");
                });

            modelBuilder.Entity("FileSystemWeb.Models.ShareFile", b =>
                {
                    b.HasOne("FileSystemWeb.Models.FileItemPermission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileSystemWeb.Models.AppUser", "User")
                        .WithMany("SharedFiles")
                        .HasForeignKey("UserId");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileSystemWeb.Models.ShareFolder", b =>
                {
                    b.HasOne("FileSystemWeb.Models.FolderItemPermission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileSystemWeb.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FileSystemWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FileSystemWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileSystemWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FileSystemWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileSystemWeb.Models.AppUser", b =>
                {
                    b.Navigation("SharedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
